language: cpp

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

dist: trusty

sudo: required

cache: 
  directories:
    - nwjs-build

compiler:
  - gcc

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install yasm  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew install yasm          ; fi
  - ./build_linux64.sh

# deploy:
#   provider: releases
#   file: build/Popcorn-Time-0.3.10_linux64.tar.xz
#   name: Build $(date +'%d.%m.%Y %R')
#   skip_cleanup: true
#   api-key:
#     secure: "IxNjbYB5ptBG6yvdTVV5otXxOYUO6L31VRxHAL/3A939MukMM6GUBlr0jcJ2mWzxvhHoo90r3RWT/81qCPH0Mf7oDCWthwuAsX1RtOVC7LinbEeLEX4Lp/To0kC2gn0dBwXSJhakkQZ4alZywRxLzV+TxiF/HYlOLuF+6ZZ5mtv6vNIylxkmaQy/KHV43LYLw7weEHafj3TSpLsKFZw0/Rqw/rKKWCMzMY750HmN0rNb54Hbu9+5zVdNpnfa4ovmdTiB7aOjrr2/Z8LVYdw9+MTipwpYq4Kb2syYjkZiduUshI+ttsyw6T5Hgg0hrAnW3pVZ+HLnxQUw75BnUOoF3rFFEdLA3tGQ1BGf2zRoN10JQae/hBAvagY5Y+55m02IUE1qnOCJ6vrAfMb2a1i4Eu+JUCViMw/ITKEYnGkHWyvZ1uhT3M8WqEUAZWCnNlRz2+UjZD4dXOwQwvYzBG5smDW2H1/Z0XRUJjCGU+G5Gvol4qa7Dsb97d6ezQvtqs//DI80Af0IgQawiBVwMboLlgqUCra6+1WqlwzVk22OznkBR3zJDTqJwNkBrXhzmpy6/y2MiqcsctgMsJHClHHy4CD3PK4LplO1IHs0Ix/QZEN6gBUN3vsJsgZjhUuiPD8p0rsnxeCC8XF7GnhJOnnh6RpzF7ZOs1FjcQ+iEixgMGY="
# notifications:
#   email: false
